# Generated by Django 3.0.5 on 2020-09-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=20)),
                ('idade', models.IntegerField(default=0)),
                ('identificacao', models.CharField(max_length=5)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=20)),
                ('preco', models.FloatField(default=0)),
            ],
        ),
    ]
