# Generated by Django 3.0.5 on 2020-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_id', models.IntegerField(blank=True, null=True)),
                ('produto_id', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.FloatField(blank=True, max_length=10, null=True)),
                ('valor_total', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
